Repository wakeuplabs-io/sovryn-dapp, pull requests merged in 2024-08, with the labels that each got.

#2 SAF-13 Withdraw components
  apps/frontend/src/app/5_pages/AavePage/components/LendPositionsList/components/LendPositionAction/LendPositionAction.tsx
  apps/frontend/src/app/5_pages/AavePage/components/LendPositionsList/components/WithdrawModal/WithdrawForm.tsx
  apps/frontend/src/app/5_pages/AavePage/components/LendPositionsList/components/WithdrawModal/WithdrawModalContainer.tsx
  apps/frontend/src/locales/en/translations.json
Labels: hold

#7 SAF-40 Pool details page and layout setup
  apps/frontend/src/app/5_pages/AavePage/components/BorrowAssetsList/components/BorrowAssetAction/BorrowAssetAction.tsx
  apps/frontend/src/app/5_pages/AavePage/components/LendAssetsList/components/LendAssetAction/LendAssetAction.tsx
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/AaveReserveOverviewPage.tsx
  apps/frontend/src/locales/en/translations.json
  apps/frontend/src/router.tsx
Labels: enhancement

#6 SAF 36 - Cleanups
  apps/frontend/src/app/2_molecules/AssetAmountInput/AssetAmountInput.tsx
  apps/frontend/src/app/2_molecules/AssetAmountPriceRenderer/AssetAmountPriceRenderer.tsx
  apps/frontend/src/app/5_pages/AavePage/components/BorrowAssetsList/BorrowAssetsList.constants.tsx
  apps/frontend/src/app/5_pages/AavePage/components/BorrowAssetsList/components/BorrowAssetDetails/BorrowAssetDetails.tsx
  apps/frontend/src/app/5_pages/AavePage/components/BorrowAssetsList/components/BorrowModal/BorrowForm.tsx
  apps/frontend/src/app/5_pages/AavePage/components/BorrowPositionsList/BorrowPositionsList.constants.tsx
  apps/frontend/src/app/5_pages/AavePage/components/BorrowPositionsList/components/BorrowPositionDetails/BorrowPositionDetails.tsx
  apps/frontend/src/app/5_pages/AavePage/components/LendAssetsList/LendAssetsList.constants.tsx
  apps/frontend/src/app/5_pages/AavePage/components/LendAssetsList/components/LendAssetDetails/LendAssetDetails.tsx
  apps/frontend/src/app/5_pages/AavePage/components/LendPositionsList/LendPositionsList.constants.tsx
  apps/frontend/src/app/5_pages/AavePage/components/LendPositionsList/components/LendPositionDetails/LendPositionDetails.tsx
  apps/frontend/src/app/5_pages/AavePage/components/LendPositionsList/components/WithdrawModal/WithdrawForm.tsx
  apps/frontend/src/locales/en/translations.json
Labels: enhancement

#8 SAF-43 Wallet overview card
  apps/frontend/src/app/2_molecules/AssetAmountPriceRenderer/AssetAmountPriceRenderer.tsx
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/AaveReserveOverviewPage.tsx
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/components/WalletOverview/WalletOverview.tsx
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/components/WalletOverview/components/BorrowAction/BorrowAction.tsx
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/components/WalletOverview/components/SupplyAction/SupplyAction.tsx
  apps/frontend/src/locales/en/translations.json
Labels: enhancement

#9 SAF 42 mock EMode card
  apps/frontend/src/app/2_molecules/StatisticsCard/StatisticsCard.tsx
  apps/frontend/src/app/5_pages/AavePage/components/TopPanel/TopPanel.tsx
  apps/frontend/src/app/5_pages/AavePage/components/TopPanel/components/WalletStatCard/WalletStatCard.tsx
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/AaveReserveOverviewPage.tsx
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/components/EModeDetails/EModeDetails.tsx
  apps/frontend/src/locales/en/translations.json
Labels: enhancement

#13 Cleanup
  apps/frontend/src/app/1_atoms/Icons/Icons.tsx
  apps/frontend/src/app/2_molecules/AssetAmountInput/AssetAmountInput.tsx
  apps/frontend/src/app/2_molecules/AssetAmountPriceRenderer/AssetAmountPriceRenderer.tsx
  apps/frontend/src/app/2_molecules/MaxButton/MaxButton.tsx
  apps/frontend/src/app/2_molecules/StatisticsCard/StatisticsCard.tsx
  apps/frontend/src/app/5_pages/AavePage/AavePage.tsx
  apps/frontend/src/app/5_pages/AavePage/components/BorrowAssetsList/BorrowAssetsList.tsx
  apps/frontend/src/app/5_pages/AavePage/components/BorrowAssetsList/components/BorrowAssetAction/BorrowAssetAction.tsx
  apps/frontend/src/app/5_pages/AavePage/components/BorrowAssetsList/components/BorrowAssetDetails/BorrowAssetDetails.tsx
  apps/frontend/src/app/5_pages/AavePage/components/BorrowAssetsList/components/BorrowModal/BorrowForm.tsx
  apps/frontend/src/app/5_pages/AavePage/components/BorrowPositionsList/BorrowPositionsList.constants.tsx
  apps/frontend/src/app/5_pages/AavePage/components/BorrowPositionsList/BorrowPositionsList.tsx
  apps/frontend/src/app/5_pages/AavePage/components/BorrowPositionsList/components/BorrowPositionDetails/BorrowPositionDetails.tsx
  apps/frontend/src/app/5_pages/AavePage/components/BorrowPositionsList/components/EfficiencyModeCard/EfficiencyModeCard.tsx
  apps/frontend/src/app/5_pages/AavePage/components/BorrowPositionsList/components/RepayModal/RepayModalContainer.tsx
  apps/frontend/src/app/5_pages/AavePage/components/BorrowPositionsList/components/RepayModal/RepayWithWalletBalanceForm.tsx
  apps/frontend/src/app/5_pages/AavePage/components/CollateralRatioHealthBar/CollateralRatioHealthBar.tsx
  apps/frontend/src/app/5_pages/AavePage/components/LendAssetsList/LendAssetsList.constants.tsx
  apps/frontend/src/app/5_pages/AavePage/components/LendAssetsList/LendAssetsList.tsx
  apps/frontend/src/app/5_pages/AavePage/components/LendAssetsList/components/LendAssetDetails/LendAssetDetails.tsx
  apps/frontend/src/app/5_pages/AavePage/components/LendPositionsList/LendPositionsList.constants.tsx
  apps/frontend/src/app/5_pages/AavePage/components/LendPositionsList/LendPositionsList.tsx
  apps/frontend/src/app/5_pages/AavePage/components/LendPositionsList/components/LendPositionDetails/LendPositionDetails.tsx
  apps/frontend/src/app/5_pages/AavePage/components/PoolPositionStat/PoolPositionStat.tsx
  apps/frontend/src/app/5_pages/AavePage/components/TopPanel/TopPanel.tsx
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/AaveReserveOverviewPage.tsx
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/components/EModeDetails/EModeDetails.tsx
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/components/TopPanel/TopPanel.tsx
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/components/WalletOverview/WalletOverview.tsx
  apps/frontend/src/locales/en/translations.json
Labels: enhancement

#14 Mocked table cards plus refactor of statistics card
  apps/frontend/src/app/1_atoms/Icons/Icons.tsx
  apps/frontend/src/app/2_molecules/StatisticsCard/StatisticsCard.tsx
  apps/frontend/src/app/5_pages/AavePage/components/TopPanel/TopPanel.tsx
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/AaveReserveOverviewPage.tsx
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/components/BorrowDetailsGraph/BorrowDetailsGraph.tsx
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/components/EModeDetails/EModeDetails.tsx
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/components/InterestRateModelGraph/InterestRateModelGraph.tsx
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/components/SupplyDetailsGraph/SupplyDetailsGraph.tsx
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/components/TopPanel/TopPanel.tsx
  apps/frontend/src/locales/en/translations.json
Labels: enhancement

#16 Saf 41 charts
  apps/frontend/package.json
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/components/BorrowDetailsGraph/BorrowDetailsGraph.tsx
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/components/BorrowDetailsGraph/components/Chart/Chart.constants.ts
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/components/BorrowDetailsGraph/components/Chart/Chart.tsx
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/components/BorrowDetailsGraph/components/Chart/Chart.types.ts
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/components/BorrowDetailsGraph/components/Chart/Chart.utils.ts
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/components/InterestRateModelGraph/InterestRateModelGraph.tsx
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/components/InterestRateModelGraph/components/Chart/Chart.constants.ts
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/components/InterestRateModelGraph/components/Chart/Chart.tsx
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/components/InterestRateModelGraph/components/Chart/Chart.types.ts
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/components/InterestRateModelGraph/components/Chart/Chart.utils.ts
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/components/SupplyDetailsGraph/SupplyDetailsGraph.tsx
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/components/SupplyDetailsGraph/components/Chart/Chart.constants.ts
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/components/SupplyDetailsGraph/components/Chart/Chart.tsx
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/components/SupplyDetailsGraph/components/Chart/Chart.types.ts
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/components/SupplyDetailsGraph/components/Chart/Chart.utils.ts
  apps/frontend/src/locales/en/translations.json
Labels: enhancement

#15 Dashboard pool data integration
  apps/frontend/package.json
  apps/frontend/src/app/2_molecules/AssetAmountPriceRenderer/AssetAmountPriceRenderer.tsx
  apps/frontend/src/app/2_molecules/StatisticsCard/StatisticsCard.tsx
  apps/frontend/src/app/5_pages/AavePage/AavePage.tsx
  apps/frontend/src/app/5_pages/AavePage/components/BorrowAssetsList/BorrowAssetsList.constants.tsx
  apps/frontend/src/app/5_pages/AavePage/components/BorrowAssetsList/BorrowAssetsList.tsx
  apps/frontend/src/app/5_pages/AavePage/components/BorrowAssetsList/BorrowAssetsList.types.tsx
  apps/frontend/src/app/5_pages/AavePage/components/BorrowAssetsList/components/BorrowAssetDetails/BorrowAssetDetails.tsx
  apps/frontend/src/app/5_pages/AavePage/components/BorrowPositionsList/BorrowPositionsList.constants.tsx
  apps/frontend/src/app/5_pages/AavePage/components/BorrowPositionsList/BorrowPositionsList.tsx
  apps/frontend/src/app/5_pages/AavePage/components/BorrowPositionsList/BorrowPositionsList.types.tsx
  apps/frontend/src/app/5_pages/AavePage/components/BorrowPositionsList/components/BorrowPositionDetails/BorrowPositionDetails.tsx
  apps/frontend/src/app/5_pages/AavePage/components/BorrowPositionsList/components/EfficiencyModeCard/EfficiencyModeCard.tsx
  apps/frontend/src/app/5_pages/AavePage/components/LendAssetsList/LendAssetsList.constants.tsx
  apps/frontend/src/app/5_pages/AavePage/components/LendAssetsList/LendAssetsList.tsx
  apps/frontend/src/app/5_pages/AavePage/components/LendAssetsList/LendAssetsList.types.tsx
  apps/frontend/src/app/5_pages/AavePage/components/LendAssetsList/components/AssetBalance/AssetBalance.tsx
  apps/frontend/src/app/5_pages/AavePage/components/LendAssetsList/components/LendAssetDetails/LendAssetDetails.tsx
  apps/frontend/src/app/5_pages/AavePage/components/LendPositionsList/LendPositionsList.constants.tsx
  apps/frontend/src/app/5_pages/AavePage/components/LendPositionsList/LendPositionsList.tsx
  apps/frontend/src/app/5_pages/AavePage/components/LendPositionsList/LendPositionsList.types.tsx
  apps/frontend/src/app/5_pages/AavePage/components/LendPositionsList/components/LendPositionDetails/LendPositionDetails.tsx
  apps/frontend/src/app/5_pages/AavePage/components/TopPanel/TopPanel.tsx
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/components/WalletOverview/components/BorrowAction/BorrowAction.tsx
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/components/WalletOverview/components/SupplyAction/SupplyAction.tsx
  apps/frontend/src/constants/aave.ts
  apps/frontend/src/hooks/useAaveReservesData.tsx
  apps/frontend/src/hooks/useAaveUserReservesData.tsx
  apps/frontend/src/locales/en/translations.json
  apps/frontend/src/utils/aave.ts
  apps/frontend/src/utils/graphql/bob/generated.tsx
  apps/frontend/src/utils/graphql/mynt/generated.tsx
  apps/frontend/src/utils/graphql/rsk/generated.tsx
  apps/frontend/src/utils/graphql/zero/generated.tsx
  yarn.lock
Labels: enhancement

#18 fix breakpoints
  apps/frontend/src/app/5_pages/AavePage/AavePage.tsx
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/AaveReserveOverviewPage.tsx
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/components/BorrowDetailsGraph/components/Chart/Chart.tsx
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/components/InterestRateModelGraph/components/Chart/Chart.tsx
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/components/SupplyDetailsGraph/components/Chart/Chart.tsx
Labels: bug, enhancement

#20 [SAF-41] fix color constant and background for mobile vs desktop views
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/AaveReserveOverviewPage.tsx
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/components/BorrowDetailsGraph/BorrowDetailsGraph.tsx
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/components/BorrowDetailsGraph/components/Chart/Chart.constants.ts
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/components/BorrowDetailsGraph/components/Chart/Chart.tsx
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/components/InterestRateModelGraph/InterestRateModelGraph.tsx
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/components/InterestRateModelGraph/components/Chart/Chart.constants.ts
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/components/InterestRateModelGraph/components/Chart/Chart.tsx
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/components/SupplyDetailsGraph/SupplyDetailsGraph.tsx
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/components/SupplyDetailsGraph/components/Chart/Chart.constants.ts
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/components/SupplyDetailsGraph/components/Chart/Chart.tsx
  apps/frontend/src/locales/en/translations.json
Labels: bug, enhancement

#23 Cache for aave hooks
  apps/frontend/src/app/1_atoms/Icons/Icons.tsx
  apps/frontend/src/app/5_pages/AavePage/AavePage.tsx
  apps/frontend/src/app/5_pages/AavePage/components/LendAssetsList/components/LendModal/LendForm.tsx
  apps/frontend/src/app/5_pages/AavePage/components/LendPositionsList/LendPositionsList.constants.tsx
  apps/frontend/src/app/5_pages/AavePage/components/LendPositionsList/components/LendPositionAction/LendPositionAction.tsx
  apps/frontend/src/app/5_pages/AavePage/components/LendPositionsList/components/WithdrawModal/WithdrawForm.tsx
  apps/frontend/src/app/5_pages/AavePage/components/LendPositionsList/components/WithdrawModal/WithdrawModalContainer.tsx
  apps/frontend/src/hooks/aave/useAaveDeposit.tsx
  apps/frontend/src/hooks/aave/useAaveReservesData.tsx
  apps/frontend/src/hooks/aave/useAaveUserReservesData.tsx
  apps/frontend/src/hooks/aave/useAaveWithdraw.tsx
  apps/frontend/src/hooks/useAaveUserReservesData.tsx
  apps/frontend/src/locales/en/translations.json
  apps/frontend/src/utils/aave/AaveSupplyTransactionsFactory.ts
  apps/frontend/src/utils/aave/AaveWithdrawTransactionsFactory.ts
  packages/contracts/src/contracts/assets/bobTestnet.ts
Labels: enhancement, hold

#25 Develop mockups
  apps/frontend/src/app/5_pages/AavePage/AavePage.tsx
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/AaveReserveOverviewPage.tsx
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/components/BorrowDetailsGraph/BorrowDetailsGraph.tsx
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/components/BorrowDetailsGraph/components/Chart/Chart.constants.ts
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/components/BorrowDetailsGraph/components/Chart/Chart.tsx
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/components/InterestRateModelGraph/InterestRateModelGraph.tsx
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/components/InterestRateModelGraph/components/Chart/Chart.constants.ts
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/components/InterestRateModelGraph/components/Chart/Chart.tsx
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/components/SupplyDetailsGraph/SupplyDetailsGraph.tsx
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/components/SupplyDetailsGraph/components/Chart/Chart.constants.ts
  apps/frontend/src/app/5_pages/AaveReserveOverviewPage/components/SupplyDetailsGraph/components/Chart/Chart.tsx
  apps/frontend/src/locales/en/translations.json
Labels: enhancement

#24 Borrow integration
  apps/frontend/src/app/2_molecules/AavePoolRowTitle/AavePoolRowTitle.tsx
  apps/frontend/src/app/5_pages/AavePage/components/BorrowAssetsList/components/BorrowAssetAction/BorrowAssetAction.tsx
  apps/frontend/src/app/5_pages/AavePage/components/BorrowAssetsList/components/BorrowModal/BorrowForm.tsx
  apps/frontend/src/app/5_pages/AavePage/components/BorrowAssetsList/components/BorrowModal/BorrowForm.utils.ts
  apps/frontend/src/app/5_pages/AavePage/components/BorrowAssetsList/components/BorrowModal/BorrowModalContainer.tsx
  apps/frontend/src/app/5_pages/AavePage/components/CollateralRatioHealthBar/CollateralRatioHealthBar.tsx
  apps/frontend/src/app/5_pages/AavePage/components/CollateralRatioHealthBar/CollateralRatioHealthBar.utils.tsx
  apps/frontend/src/app/5_pages/AavePage/components/LendAssetsList/components/LendModal/LendForm.tsx
  apps/frontend/src/constants/aave.ts
  apps/frontend/src/hooks/aave/useAaveBorrow.tsx
  apps/frontend/src/locales/en/translations.json
  apps/frontend/src/utils/aave.ts
  apps/frontend/src/utils/aave/AaveBorrowTransactionsFactory.ts
  yarn.lock
Labels: enhancement

#26 Repay integration
  apps/frontend/src/app/2_molecules/AmountRenderer/AmountRenderer.tsx
  apps/frontend/src/app/5_pages/AavePage/AavePage.tsx
  apps/frontend/src/app/5_pages/AavePage/components/BorrowAssetsList/BorrowAssetsList.constants.tsx
  apps/frontend/src/app/5_pages/AavePage/components/BorrowPositionsList/BorrowPositionsList.constants.tsx
  apps/frontend/src/app/5_pages/AavePage/components/BorrowPositionsList/BorrowPositionsList.types.tsx
  apps/frontend/src/app/5_pages/AavePage/components/BorrowPositionsList/components/BorrowPositionAction/BorrowPositionAction.tsx
  apps/frontend/src/app/5_pages/AavePage/components/BorrowPositionsList/components/BorrowPositionDetails/BorrowPositionDetails.tsx
  apps/frontend/src/app/5_pages/AavePage/components/BorrowPositionsList/components/RepayModal/RepayModalContainer.tsx
  apps/frontend/src/app/5_pages/AavePage/components/BorrowPositionsList/components/RepayModal/RepayWithWalletBalanceForm.tsx
  apps/frontend/src/app/5_pages/AavePage/components/CollateralRatioHealthBar/CollateralRatioHealthBar.tsx
  apps/frontend/src/app/5_pages/AavePage/components/LendAssetsList/LendAssetsList.constants.tsx
  apps/frontend/src/hooks/aave/useAaveRepay.tsx
  apps/frontend/src/hooks/aave/useAaveUserReservesData.tsx
  apps/frontend/src/locales/en/translations.json
  apps/frontend/src/utils/aave.ts
  apps/frontend/src/utils/aave/AaveRepayTransactionsFactory.ts
  apps/frontend/src/utils/aave/AaveUserReservesSummary.ts
Labels: enhancement

#29 SAF-49 setup bob
  apps/frontend/src/app/2_molecules/AssetAmountInput/AssetAmountInput.tsx
  apps/frontend/src/app/5_pages/AavePage/AavePage.tsx
  apps/frontend/src/app/5_pages/AavePage/AavePage.utils.tsx
  apps/frontend/src/app/5_pages/AavePage/components/BorrowAssetsList/BorrowAssetsList.constants.tsx
  apps/frontend/src/app/5_pages/AavePage/components/BorrowAssetsList/BorrowAssetsList.tsx
  apps/frontend/src/app/5_pages/AavePage/components/BorrowAssetsList/components/BorrowAssetAction/BorrowAssetAction.tsx
  apps/frontend/src/app/5_pages/AavePage/components/BorrowAssetsList/components/BorrowAssetDetails/BorrowAssetDetails.tsx
  apps/frontend/src/app/5_pages/AavePage/components/BorrowAssetsList/components/BorrowModal/BorrowForm.tsx
  apps/frontend/src/app/5_pages/AavePage/components/BorrowAssetsList/components/BorrowModal/BorrowForm.utils.ts
  apps/frontend/src/app/5_pages/AavePage/components/BorrowAssetsList/components/BorrowModal/BorrowModalContainer.tsx
  apps/frontend/src/app/5_pages/AavePage/components/BorrowPositionsList/BorrowPositionsList.constants.tsx
  apps/frontend/src/app/5_pages/AavePage/components/BorrowPositionsList/BorrowPositionsList.tsx
  apps/frontend/src/app/5_pages/AavePage/components/BorrowPositionsList/BorrowPositionsList.types.tsx
  apps/frontend/src/app/5_pages/AavePage/components/BorrowPositionsList/components/BorrowPositionAction/BorrowPositionAction.tsx
  apps/frontend/src/app/5_pages/AavePage/components/BorrowPositionsList/components/BorrowPositionDetails/BorrowPositionDetails.tsx
  apps/frontend/src/app/5_pages/AavePage/components/BorrowPositionsList/components/RepayForm/RepayForm.tsx
  apps/frontend/src/app/5_pages/AavePage/components/BorrowPositionsList/components/RepayForm/RepayWithCollateralForm.tsx
  apps/frontend/src/app/5_pages/AavePage/components/BorrowPositionsList/components/RepayForm/RepayWithWalletBalanceForm.tsx
  apps/frontend/src/app/5_pages/AavePage/components/BorrowPositionsList/components/RepayModal/RepayModalContainer.tsx
  apps/frontend/src/app/5_pages/AavePage/components/CollateralRatioHealthBar/CollateralRatioHealthBar.tsx
  apps/frontend/src/app/5_pages/AavePage/components/CollateralRatioHealthBar/CollateralRatioHealthBar.utils.tsx
  apps/frontend/src/app/5_pages/AavePage/components/LendAssetsList/LendAssetsList.constants.tsx
  apps/frontend/src/app/5_pages/AavePage/components/LendAssetsList/LendAssetsList.tsx
  apps/frontend/src/app/5_pages/AavePage/components/LendAssetsList/LendAssetsList.types.tsx
  apps/frontend/src/app/5_pages/AavePage/components/LendAssetsList/components/AssetBalance/AssetBalance.tsx
  apps/frontend/src/app/5_pages/AavePage/components/LendAssetsList/components/LendAssetAction/LendAssetAction.tsx
  apps/frontend/src/app/5_pages/AavePage/components/LendAssetsList/components/LendAssetDetails/LendAssetDetails.tsx
  apps/frontend/src/app/5_pages/AavePage/components/LendAssetsList/components/LendForm/LendForm.tsx
  apps/frontend/src/app/5_pages/AavePage/components/LendAssetsList/components/LendModal/LendModalContainer.tsx
  apps/frontend/src/app/5_pages/AavePage/components/LendPositionsList/LendPositionsList.constants.tsx
  apps/frontend/src/app/5_pages/AavePage/components/LendPositionsList/LendPositionsList.tsx
  apps/frontend/src/app/5_pages/AavePage/components/LendPositionsList/components/LendPositionAction/LendPositionAction.tsx
  apps/frontend/src/app/5_pages/AavePage/components/LendPositionsList/components/LendPositionDetails/LendPositionDetails.tsx
  apps/frontend/src/app/5_pages/AavePage/components/LendPositionsList/components/WithdrawForm/WithdrawForm.tsx
  apps/frontend/src/app/5_pages/AavePage/components/LendPositionsList/components/WithdrawModal/WithdrawModalContainer.tsx
  apps/frontend/src/app/5_pages/AavePage/components/TopPanel/TopPanel.tsx
  apps/frontend/src/constants/aave.ts
  apps/frontend/src/hooks/aave/useAaveRepay.tsx
  apps/frontend/src/hooks/aave/useAaveReservesData.tsx
  apps/frontend/src/hooks/aave/useAaveUserReservesData.tsx
  apps/frontend/src/locales/en/translations.json
  apps/frontend/src/utils/aave/AaveCalculations.ts
  apps/frontend/src/utils/aave/AaveRepayTransactionsFactory.ts
  apps/frontend/src/utils/aave/AaveSupplyTransactionsFactory.ts
  apps/frontend/src/utils/aave/AaveUserReservesSummary.ts
  packages/contracts/src/contracts/assets/bobTestnet.ts
Labels: enhancement, merge conflicts
